### ISSUE TITLE
chmod: /app/laravel/.docker-rootless/s6: No such file or directory

### ISSUE THREAD

**Issue by cgfeel** [khs1994-docker/laravel-demo#3]
我看`Dockerfile`中第98行 https://github.com/khs1994-docker/laravel-demo/blob/master/Dockerfile#L98 中写到
```
    && chmod -R +x /app/laravel-docker/.docker-rootless/s6 \
```
请问`*/.docker-rootless/s6`是从哪来来的，也没有看到执行`copy`
---
备注：
> 项目目录我改成了`/app/laravel`，这个和文档不同，但没有问题

**Comment by khs1994** [comment]
* https://github.com/khs1994-docker/laravel-demo/tree/master/patch

把这个文件夹的内容复制到你的 laravel 项目

**Comment by cgfeel** [comment]
> * https://github.com/khs1994-docker/laravel-demo/tree/master/patch
> 
> 把这个文件夹的内容复制到你的 laravel 项目

我试试

**Comment by aiyuchen** [comment]
> * https://github.com/khs1994-docker/laravel-demo/tree/master/patch
> 
> 把这个文件夹的内容复制到你的 laravel 项目

感谢

**Comment by cgfeel** [comment]
> * https://github.com/khs1994-docker/laravel-demo/tree/master/patch
> 
> 把这个文件夹的内容复制到你的 laravel 项目

感谢
